use native launchers in bash tests
cleanup Build.scala

diff --git a/dist/bin/common-shared b/dist/bin/common-shared
--- a/dist/bin/common-shared
+++ b/dist/bin/common-shared
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+# Common options for both scala-cli and java based launchers
+
 #/*--------------------------------------------------------------------------
 # *  Credits: This script is based on the script generated by sbt-pack.
 # *--------------------------------------------------------------------------*/
@@ -22,10 +24,6 @@ function onExit() {
   [[ "$saved_stty" != "" ]] && restoreSttySettings
   exit $scala_exit_status
 }
-
-#/*--------------------------------------------------------------------------
-# *  SECTION FOR JAVA COMMAND
-# *--------------------------------------------------------------------------*/
 
 # to reenable echo if we are interrupted before completing.
 trap onExit INT TERM EXIT
@@ -71,16 +69,55 @@ if [[ ${cygwin-} || ${mingw-} || ${msys-} ]]; then
   esac
 fi
 
-source "$PROG_HOME/bin/cli-common-platform"
+# Resolve JAVA_HOME from javac command path
+if [ -z "$JAVA_HOME" ]; then
+  javaExecutable="`which javac`"
+  if [ -n "$javaExecutable" -a -f "$javaExecutable" -a ! "`expr \"$javaExecutable\" : '\([^ ]*\)'`" = "no" ]; then
+    # readlink(1) is not available as standard on Solaris 10.
+    readLink=`which readlink`
+    if [ ! `expr "$readLink" : '\([^ ]*\)'` = "no" ]; then
+      javaExecutable="`readlink -f \"$javaExecutable\"`"
+      javaHome="`dirname \"$javaExecutable\"`"
+      javaHome=`expr "$javaHome" : '\(.*\)/bin'`
+      JAVA_HOME="$javaHome"
+      export JAVA_HOME
+    fi
+  fi
+fi
+
+if [ -z "${JAVACMD-}" ] ; then
+  if [ -n "${JAVA_HOME-}"  ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+      # IBM's JDK on AIX uses strange locations for the executables
+      JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+      JAVACMD="$JAVA_HOME/bin/java"
+    fi
+  else
+    JAVACMD="`which java`"
+  fi
+fi
+
+if [ ! -x "$JAVACMD" ] ; then
+  echo "Error: JAVA_HOME is not defined correctly."
+  echo "  We cannot execute $JAVACMD"
+  exit 1
+fi
+
+if [ -z "$JAVA_HOME" ] ; then
+  echo "Warning: JAVA_HOME environment variable is not set."
+fi
 
 CLASSPATH_SUFFIX=""
 # Path separator used in EXTRA_CLASSPATH
 PSEP=":"
+PROG_HOME_URI="file://$PROG_HOME"
 
 # translate paths to Windows-mixed format before running java
 if [ -n "${CYGPATHCMD-}" ]; then
   [ -n "${PROG_HOME-}" ] &&
     PROG_HOME=`"$CYGPATHCMD" -am "$PROG_HOME"`
+    PROG_HOME_URI="file:///$PROG_HOME" # Add extra root dir prefix
   [ -n "$JAVA_HOME" ] &&
     JAVA_HOME=`"$CYGPATHCMD" -am "$JAVA_HOME"`
   CLASSPATH_SUFFIX=";"
@@ -89,18 +126,14 @@ elif [[ ${mingw-} || ${msys-} ]]; then
   # For Mingw / Msys, convert paths from UNIX format before anything is touched
   [ -n "$PROG_HOME" ] &&
     PROG_HOME="`(cd "$PROG_HOME"; pwd -W | sed 's|/|\\\\|g')`"
+    PROG_HOME_URI="file:///$PROG_HOME" # Add extra root dir prefix
   [ -n "$JAVA_HOME" ] &&
     JAVA_HOME="`(cd "$JAVA_HOME"; pwd -W | sed 's|/|\\\\|g')`"
   CLASSPATH_SUFFIX=";"
   PSEP=";"
 fi
 
-#/*--------------------------------------------------
-# * The code below is for Dotty
-# *-------------------------------------------------*/
-
 declare -a scala_args
-
 addScala () {
   scala_args+=("'$1'")
 }
