step 1: basic script that forwards to prebuilt launcher and overrides default scala-version
[Cherry-picked 4d291fb3b68867d5a970faad52d1ab5a861b395a]

diff --git a/dist/bin/scala b/dist/bin/scala
--- a/dist/bin/scala
+++ b/dist/bin/scala
@@ -26,47 +26,27 @@ if [ -z "${PROG_HOME-}" ] ; then
   cd "$saveddir"
 fi
 
-source "$PROG_HOME/bin/common"
+source "$PROG_HOME/bin/cli-common"
 
-while [[ $# -gt 0 ]]; do
-  case "$1" in
-    -D*)
-      # pass to scala as well: otherwise we lose it sometimes when we
-      # need it, e.g. communicating with a server compiler.
-      # respect user-supplied -Dscala.usejavacp
-      addJava "$1"
-      addScala "$1"
-      shift
-      ;;
-    -J*)
-      # as with -D, pass to scala even though it will almost
-      # never be used.
-      addJava "${1:2}"
-      addScala "$1"
-      shift
-      ;;
-    -classpath*)
-      if [ "$1" != "${1##* }" ]; then
-        # -classpath and its value have been supplied in a single string e.g. "-classpath 'lib/*'"
-        A=$1 ; shift # consume $1 before adding its substrings back
-        set -- $A "$@" # split $1 on whitespace and put it back
-      else
-        addScala "$1"
-        shift
-      fi
-      ;;
-    *)
-      addScala "$1"
-      shift
-      ;;
-  esac
-done
+SCALA_VERSION=""
+# iterate through lines in VERSION_SRC
+while IFS= read -r line; do
+  # if line starts with "version:=" then extract the version
+  if [[ "$line" == version:=* ]]; then
+    SCALA_VERSION="${line#version:=}"
+    break
+  fi
+done < "$PROG_HOME/VERSION"
+
+# assert that SCALA_VERSION is not empty
+if [ -z "$SCALA_VERSION" ]; then
+  echo "Failed to extract Scala version from $PROG_HOME/VERSION"
+  exit 1
+fi
 
 # exec here would prevent onExit from being called, leaving terminal in unusable state
-compilerJavaClasspathArgs
 [ -z "${ConEmuPID-}" -o -n "${cygwin-}" ] && export MSYSTEM= PWD= # workaround for #12405
-eval "\"$JAVACMD\"" "${java_args[@]}" "-Dscala.home=\"$PROG_HOME\"" "-classpath \"$jvm_cp_args\"" "dotty.tools.MainGenericRunner" "-classpath \"$jvm_cp_args\"" "${scala_args[@]}"
+eval "\"$SCALA_CLI_LAUNCHER\"" "--cli-default-scala-version \"$SCALA_VERSION\"" "$@"
 scala_exit_status=$?
-
 
 onExit
