Simplify CI builds (#3084)
Remove matrix build. Use groups to parallelise tests. Cleanup CI scripts

diff --git a/project/scripts/sbt b/project/scripts/sbt
--- a/project/scripts/sbt
+++ b/project/scripts/sbt
@@ -1,26 +1,19 @@
 #!/usr/bin/env bash
 
-CI_TEST=$1
+# Usage:
+# ./sbt <cmd>
 
-if [ -n "$2" ]; then
-  if [ $2 = true ]; then
-    SHOULD_RUN=true
-  else
-    SHOULD_RUN=false
-  fi
-else
-  SHOULD_RUN=true
+CMD="$1"
+
+if [ -z "$CMD" ]; then
+  echo "Error: missing sbt command"
+  exit 1
 fi
 
-if [ $SHOULD_RUN = true ]; then
-  # get the ivy2 cache:
-  ln -s /var/cache/drone/ivy2 "$HOME/.ivy2" || true
-
-  # run sbt with the supplied arg:
-  sbt -J-Xmx4096m \
-      -J-XX:ReservedCodeCacheSize=512m \
-      -J-XX:MaxMetaspaceSize=1024m \
-      -Ddotty.drone.mem=4096m "$CI_TEST"
-else
-  echo "Not running, \$2=$2, SHOULD_RUN=$SHOULD_RUN"
-fi
+# run sbt with the supplied arg
+sbt -J-Xmx4096m \
+    -J-XX:ReservedCodeCacheSize=512m \
+    -J-XX:MaxMetaspaceSize=1024m \
+    -Ddotty.drone.mem=4096m \
+    -ivy /var/cache/drone/ivy2 \
+    "$CMD"
diff --git a/project/scripts/sbtPublish b/project/scripts/sbtPublish
--- a/project/scripts/sbtPublish
+++ b/project/scripts/sbtPublish
@@ -1,32 +1,26 @@
 #!/usr/bin/env bash
 
-# If the script should publish to maven:
-SHOULD_RUN=$1
+# Usage:
+# SONATYPE_USER=<sonatype user> SONATYPE_PW=<sonatype pw> PGP_PW=<pgp pw> ./sbtPublish <publish cmd>
 
-# Sonatype credentials:
-SONATYPE_USER=$2
-SONATYPE_PW=$3
-
-# PGP Credentials:
-PGP_PW=$4
+set -e
 
 # Release command:
-RELEASE_CMD=$5
+RELEASE_CMD="$1"
 
-if [ $SHOULD_RUN = false ]; then
-  exit 0
-fi
-
-if [ -z "$2" -o -z "$3" -o -z "$4" ]; then
-    echo "invalid args: this script takes 4 args, usage:"
-    echo ""
-    echo "    ./project/scripts/sbt SHOULD_RUN SONATYPE_USER SONATYPE_PW PGP_PW"
+if [ -z "$SONATYPE_USER" ] || [ -z "$SONATYPE_PW" ] || [ -z "$PGP_PW" ]; then
+    echo "Error: SONATYPE_USER, SONATYPE_PW or PGP_PW env unset"
     exit 1
 fi
 
 if [ ! "$NIGHTLYBUILD" = "yes" ] && [ ! "$RELEASEBUILD" = "yes" ]; then
-    echo "Neither NIGHTLYBUILD or RELEASEBUILD env var set to \"yes\""
+    echo "Neither NIGHTLYBUILD nor RELEASEBUILD env var set to \"yes\""
     exit 1
+fi
+
+if [ -z "$RELEASE_CMD" ]; then
+  echo "Error: missing publish command"
+  exit 1
 fi
 
 CMD="     ;set credentials in ThisBuild := Seq(Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", \"$2\", \"$3\"))"
@@ -35,8 +29,6 @@ CMD="$CMD ;set pgpSecretRing := file(\"/keys/secring.asc\")"
 CMD="$CMD ;set pgpPublicRing := file(\"/keys/pubring.asc\")"
 CMD="$CMD $RELEASE_CMD"
 
-sbt -J-Xmx4096m \
-    -J-XX:ReservedCodeCacheSize=512m \
-    -J-XX:MaxMetaspaceSize=1024m \
-    -Ddotty.drone.mem=4096m \
-    "$CMD"
+# run sbt with the supplied arg
+SBT="$(cd "$(dirname "${BASH_SOURCE[0]}")" >& /dev/null && pwd)/sbt"
+eval "$SBT" "$CMD"
