Improve Shell scripts
* Remove unneeded SHA trim (The Scala code have already used `String#subString` to get the needed length. It would be better to let the user choose the length they need.).

diff --git a/project/scripts/build/get-scala-commit-date b/project/scripts/build/get-scala-commit-date
--- a/project/scripts/build/get-scala-commit-date
+++ b/project/scripts/build/get-scala-commit-date
@@ -8,9 +8,13 @@
 #   20120312
 #
 
+# Exit immediately if any command returns a non-zero status.
+set -eo pipefail
+
 [[ $# -eq 0 ]] || cd "$1"
 
-lastcommitdate=$(git log --format="%ci" HEAD | head -n 1 | cut -d ' ' -f 1)
-
-# 20120324
-echo "${lastcommitdate//-/}"
+# A better version could use `git log -n 1 --pretty='format:%cd' --date=format:'%Y%m%d'`.
+# But it requires everybody to use Git v2.6.0 or above.
+last_commit_date=$(git log -1 --format="%ci" HEAD | cut -d ' ' -f 1)
+# remove "-"
+echo "${last_commit_date//-/}"
