Disable publishing of already-published artefacts
Also disable the community build since it relies on complete
local publish of all the artefacts.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -182,103 +182,103 @@ jobs:
         run: sbt ";sjsJUnitTests/test ;sjsCompilerTests/test"
         shell: cmd
 
-  community_build_a:
-    runs-on: [self-hosted, Linux]
-    container:
-      image: lampepfl/dotty:2021-03-22
-      options: --cpu-shares 4096
-      volumes:
-        - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
-        - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
-        - ${{ github.workspace }}/../../cache/general:/root/.cache
-    if: "github.event_name == 'schedule' && github.repository == 'lampepfl/dotty'
-         || github.event_name == 'push'
-         || (
-           github.event_name == 'pull_request'
-           && !contains(github.event.pull_request.body, '[skip ci]')
-           && !contains(github.event.pull_request.body, '[skip community_build]')
-         )
-         || (
-           github.event_name == 'workflow_dispatch'
-           && github.repository == 'lampepfl/dotty'
-         )"
+  # community_build_a:
+  #   runs-on: [self-hosted, Linux]
+  #   container:
+  #     image: lampepfl/dotty:2021-03-22
+  #     options: --cpu-shares 4096
+  #     volumes:
+  #       - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
+  #       - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
+  #       - ${{ github.workspace }}/../../cache/general:/root/.cache
+  #   if: "github.event_name == 'schedule' && github.repository == 'lampepfl/dotty'
+  #        || github.event_name == 'push'
+  #        || (
+  #          github.event_name == 'pull_request'
+  #          && !contains(github.event.pull_request.body, '[skip ci]')
+  #          && !contains(github.event.pull_request.body, '[skip community_build]')
+  #        )
+  #        || (
+  #          github.event_name == 'workflow_dispatch'
+  #          && github.repository == 'lampepfl/dotty'
+  #        )"
 
-    steps:
-      - name: Reset existing repo
-        run: git -c "http.https://github.com/.extraheader=" fetch --recurse-submodules=no "https://github.com/lampepfl/dotty" && git reset --hard FETCH_HEAD || true
+  #   steps:
+  #     - name: Reset existing repo
+  #       run: git -c "http.https://github.com/.extraheader=" fetch --recurse-submodules=no "https://github.com/lampepfl/dotty" && git reset --hard FETCH_HEAD || true
 
-      - name: Checkout cleanup script
-        uses: actions/checkout@v2
+  #     - name: Checkout cleanup script
+  #       uses: actions/checkout@v2
 
-      - name: Cleanup
-        run: .github/workflows/cleanup.sh
+  #     - name: Cleanup
+  #       run: .github/workflows/cleanup.sh
 
-      - name: Git Checkout
-        uses: actions/checkout@v2
+  #     - name: Git Checkout
+  #       uses: actions/checkout@v2
 
-      - name: Add SBT proxy repositories
-        run: cp -vf .github/workflows/repositories /root/.sbt/ ; true
+  #     - name: Add SBT proxy repositories
+  #       run: cp -vf .github/workflows/repositories /root/.sbt/ ; true
 
-      - name: Disable experimental features on release
-        if: "github.event_name == 'push'
-            && startsWith(github.event.ref, 'refs/tags/')
-            && !startsWith(github.event.ref, 'refs/tags/sbt-dotty-')"
-        run: echo "DISALLOW_EXPERIMENTAL_FEATURES=true" >> $GITHUB_ENV
+  #     - name: Disable experimental features on release
+  #       if: "github.event_name == 'push'
+  #           && startsWith(github.event.ref, 'refs/tags/')
+  #           && !startsWith(github.event.ref, 'refs/tags/sbt-dotty-')"
+  #       run: echo "DISALLOW_EXPERIMENTAL_FEATURES=true" >> $GITHUB_ENV
 
-      - name: Test
-        run: |
-          git submodule sync
-          git submodule update --init --recursive --jobs 7
-          ./project/scripts/sbt "community-build/testOnly dotty.communitybuild.CommunityBuildTestA"
+  #     - name: Test
+  #       run: |
+  #         git submodule sync
+  #         git submodule update --init --recursive --jobs 7
+  #         ./project/scripts/sbt "community-build/testOnly dotty.communitybuild.CommunityBuildTestA"
 
-  community_build_b:
-    runs-on: [self-hosted, Linux]
-    container:
-      image: lampepfl/dotty:2021-03-22
-      options: --cpu-shares 4096
-      volumes:
-        - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
-        - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
-        - ${{ github.workspace }}/../../cache/general:/root/.cache
-    if: "github.event_name == 'schedule' && github.repository == 'lampepfl/dotty'
-         || github.event_name == 'push'
-         || (
-           github.event_name == 'pull_request'
-           && !contains(github.event.pull_request.body, '[skip ci]')
-           && !contains(github.event.pull_request.body, '[skip community_build]')
-         )
-         || (
-           github.event_name == 'workflow_dispatch'
-           && github.repository == 'lampepfl/dotty'
-         )"
+  # community_build_b:
+  #   runs-on: [self-hosted, Linux]
+  #   container:
+  #     image: lampepfl/dotty:2021-03-22
+  #     options: --cpu-shares 4096
+  #     volumes:
+  #       - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
+  #       - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
+  #       - ${{ github.workspace }}/../../cache/general:/root/.cache
+  #   if: "github.event_name == 'schedule' && github.repository == 'lampepfl/dotty'
+  #        || github.event_name == 'push'
+  #        || (
+  #          github.event_name == 'pull_request'
+  #          && !contains(github.event.pull_request.body, '[skip ci]')
+  #          && !contains(github.event.pull_request.body, '[skip community_build]')
+  #        )
+  #        || (
+  #          github.event_name == 'workflow_dispatch'
+  #          && github.repository == 'lampepfl/dotty'
+  #        )"
 
-    steps:
-      - name: Reset existing repo
-        run: git -c "http.https://github.com/.extraheader=" fetch --recurse-submodules=no "https://github.com/lampepfl/dotty" && git reset --hard FETCH_HEAD || true
+  #   steps:
+  #     - name: Reset existing repo
+  #       run: git -c "http.https://github.com/.extraheader=" fetch --recurse-submodules=no "https://github.com/lampepfl/dotty" && git reset --hard FETCH_HEAD || true
 
-      - name: Checkout cleanup script
-        uses: actions/checkout@v2
+  #     - name: Checkout cleanup script
+  #       uses: actions/checkout@v2
 
-      - name: Cleanup
-        run: .github/workflows/cleanup.sh
+  #     - name: Cleanup
+  #       run: .github/workflows/cleanup.sh
 
-      - name: Git Checkout
-        uses: actions/checkout@v2
+  #     - name: Git Checkout
+  #       uses: actions/checkout@v2
 
-      - name: Add SBT proxy repositories
-        run: cp -vf .github/workflows/repositories /root/.sbt/ ; true
+  #     - name: Add SBT proxy repositories
+  #       run: cp -vf .github/workflows/repositories /root/.sbt/ ; true
 
-      - name: Disable experimental features on release
-        if: "github.event_name == 'push'
-            && startsWith(github.event.ref, 'refs/tags/')
-            && !startsWith(github.event.ref, 'refs/tags/sbt-dotty-')"
-        run: echo "DISALLOW_EXPERIMENTAL_FEATURES=true" >> $GITHUB_ENV
+  #     - name: Disable experimental features on release
+  #       if: "github.event_name == 'push'
+  #           && startsWith(github.event.ref, 'refs/tags/')
+  #           && !startsWith(github.event.ref, 'refs/tags/sbt-dotty-')"
+  #       run: echo "DISALLOW_EXPERIMENTAL_FEATURES=true" >> $GITHUB_ENV
 
-      - name: Test
-        run: |
-          git submodule sync
-          git submodule update --init --recursive --jobs 7
-          ./project/scripts/sbt "community-build/testOnly dotty.communitybuild.CommunityBuildTestB"
+  #     - name: Test
+  #       run: |
+  #         git submodule sync
+  #         git submodule update --init --recursive --jobs 7
+  #         ./project/scripts/sbt "community-build/testOnly dotty.communitybuild.CommunityBuildTestB"
 
   # community_build_c:
   #   runs-on: [self-hosted, Linux]
@@ -428,7 +428,7 @@ jobs:
         - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
         - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
         - ${{ github.workspace }}/../../cache/general:/root/.cache
-    needs: [test_non_bootstrapped, test, community_build_a, community_build_b, test_sbt, test_java8]
+    needs: [test_non_bootstrapped, test, test_sbt, test_java8]
     if: "(github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && github.repository == 'lampepfl/dotty'"
     env:
       NIGHTLYBUILD: yes
@@ -511,7 +511,7 @@ jobs:
         - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
         - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
         - ${{ github.workspace }}/../../cache/general:/root/.cache
-    needs: [test_non_bootstrapped, test, community_build_a, community_build_b, test_sbt, test_java8]
+    needs: [test_non_bootstrapped, test, test_sbt, test_java8]
     if: "github.event_name == 'push'
          && startsWith(github.event.ref, 'refs/tags/')
          && !startsWith(github.event.ref, 'refs/tags/sbt-dotty-')"
@@ -645,7 +645,7 @@ jobs:
         - ${{ github.workspace }}/../../cache/sbt:/root/.sbt
         - ${{ github.workspace }}/../../cache/ivy:/root/.ivy2/cache
         - ${{ github.workspace }}/../../cache/general:/root/.cache
-    needs: [community_build_a, community_build_b, test_sbt]
+    needs: [test_sbt]
     if: "github.event_name == 'push'
          && startsWith(github.event.ref, 'refs/tags/sbt-dotty-')"
 
